"use client";

import { Wallet, ArrowRight, Play, Palette } from "lucide-react";
import Link from "next/link";
import { IntegrationsManager } from "@/components/admin/IntegrationsManager";
import { OAuthManagementCards } from "@/components/admin/OAuthManagementCards";
import { useLanguage } from "@/components/shared/LanguageProvider";

export default function AdminSettingsPage() {
  const { t } = useLanguage();
  return <main><p className="text-sm font-bold uppercase tracking-[0.22em] text-primary">{t("systemConfiguration")}</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-ink dark:text-white">{t("settingsTitle")}</h1><p className="mt-2 text-ink/55 dark:text-white/60">{t("settingsDesc")}</p><div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-ink/10 bg-white p-6 dark:border-white/10 dark:bg-[#13172b] lg:col-span-2"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><Palette className="text-primary" /><div><h2 className="font-bold text-ink dark:text-white">{t("brandingCardTitle")}</h2><p className="text-xs text-ink/55 dark:text-white/60">{t("brandingCardDesc")}</p></div></div><Link href="/admin/branding" className="inline-flex items-center gap-2 whitespace-nowrap shrink-0 rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-white shadow-md transition-all duration-200 hover:bg-primary/90 hover:shadow-lg hover:-translate-y-0.5">{t("manageBrandingBtn")} <ArrowRight size={14} /></Link></div></section><section className="rounded-2xl border border-ink/10 bg-white p-6 dark:border-white/10 dark:bg-[#13172b] lg:col-span-2"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><Play className="text-primary" /><div><h2 className="font-bold text-ink dark:text-white">{t("tutorialCardTitle")}</h2><p className="text-xs text-ink/55 dark:text-white/60">{t("tutorialCardDesc")}</p></div></div><Link href="/admin/apps/tutorials" className="inline-flex items-center gap-2 whitespace-nowrap shrink-0 rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-white shadow-md transition-all duration-200 hover:bg-primary/90 hover:shadow-lg hover:-translate-y-0.5">{t("manageTutorialsBtn")} <ArrowRight size={14} /></Link></div></section><section className="rounded-2xl border border-ink/10 bg-white p-6 dark:border-white/10 dark:bg-[#13172b] lg:col-span-2"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><Wallet className="text-primary" /><div><h2 className="font-bold text-ink dark:text-white">{t("paymentMethodsCardTitle")}</h2><p className="text-xs text-ink/55 dark:text-white/60">{t("paymentMethodsCardDesc")}</p></div></div><Link href="/admin/payments/methods" className="inline-flex items-center gap-2 whitespace-nowrap shrink-0 rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-white shadow-md transition-all duration-200 hover:bg-primary/90 hover:shadow-lg hover:-translate-y-0.5">{t("managePaymentMethodsBtn")} <ArrowRight size={14} /></Link></div></section><IntegrationsManager /><OAuthManagementCards /></div></main>;
}
