"use client";

import { Eye, Save } from "lucide-react";
import { useState } from "react";
import { VideoPlayer } from "@/components/shared/VideoPlayer";
import { CustomSelect } from "@/components/ui/CustomSelect";

type Tutorial = { videoUrl: string; videoType: "youtube" | "vimeo" | "custom"; title: string; description: string; isActive: boolean };

// Admins can edit tutorial metadata and preview the exact player before publishing.
export function TutorialEditor({ appId, initial }: { appId: string; initial?: Partial<Tutorial> }) {
  const [form, setForm] = useState<Tutorial>({ videoUrl: initial?.videoUrl ?? "", videoType: initial?.videoType ?? "youtube", title: initial?.title ?? "", description: initial?.description ?? "", isActive: initial?.isActive ?? false });
  const [message, setMessage] = useState("");
  async function save(event: React.FormEvent) { event.preventDefault(); const response = await fetch(`/api/admin/apps/${appId}/tutorial`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setMessage(response.ok ? "Tutorial saved." : "Unable to save tutorial."); }
  return <div className="grid gap-6 lg:grid-cols-[1fr_1fr]"><form onSubmit={save} className="rounded-2xl border border-ink/10 bg-white p-6"><label className="block text-sm font-semibold text-ink/60">Video URL<input required type="url" value={form.videoUrl} onChange={(event) => setForm({ ...form, videoUrl: event.target.value })} placeholder="https://youtube.com/watch?v=..." className="mt-2 h-11 w-full rounded-xl bg-paper px-4 text-sm text-ink outline-none" /></label><label className="mt-4 block text-sm font-semibold text-ink/60">Video type<div className="mt-2"><CustomSelect value={form.videoType} options={["youtube", "vimeo", "custom"].map((v) => ({ value: v, label: v === "youtube" ? "YouTube" : v === "vimeo" ? "Vimeo" : "Custom video" }))} onChange={(v) => setForm({ ...form, videoType: v as Tutorial["videoType"] })} /></div></label><label className="mt-4 block text-sm font-semibold text-ink/60">Title<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} className="mt-2 h-11 w-full rounded-xl bg-paper px-4 text-sm text-ink outline-none" /></label><label className="mt-4 block text-sm font-semibold text-ink/60">Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} rows={4} className="mt-2 min-h-[112px] h-28 w-full resize-none rounded-xl bg-paper p-4 text-sm text-ink outline-none" /></label><label className="mt-4 flex items-center gap-3 text-sm font-semibold text-ink/60"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} className="h-4 w-4 accent-primary" /> Publish tutorial</label><button className="mt-6 flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-white"><Save size={15} /> Save tutorial</button>{message && <span className="ml-3 text-sm text-[#159570]">{message}</span>}</form><section className="rounded-2xl border border-ink/10 bg-white p-6"><div className="flex items-center gap-2"><Eye size={17} className="text-primary" /><h2 className="font-bold text-ink">Preview</h2></div>{form.videoUrl ? <div className="mt-5"><VideoPlayer url={form.videoUrl} type={form.videoType} /></div> : <div className="mt-5 grid aspect-video place-items-center rounded-2xl bg-paper text-sm text-ink/40">Enter a video URL to preview.</div>}<h3 className="mt-5 text-xl font-bold text-ink">{form.title || "Tutorial title"}</h3><p className="mt-2 text-sm leading-6 text-ink/55">{form.description || "Tutorial description"}</p></section></div>;
}
